---
title: "Comparative Approach: Time Series Creation and Analysis"
date: "November 2024"
author: "Md Touhidul Islam"

---

```{r, echo=FALSE, message=FALSE, results='hide', cache=T}
# Set locale for consistent date formatting
Sys.setlocale("LC_TIME", "en_US.UTF-8")

# Load required libraries for analysis
library(dplyr)    # For data manipulation
library(ggplot2)  # For visualization
library(ggpubr)   # For publication-ready plots
library(readxl)   # For reading Excel files
library(zoo)      # For time series analysis
library(DCCA)     # For detrended cross-correlation analysis
library(sandwich) # For robust standard errors
library(tseries)  # For time series tests
library(lmtest)   # For regression diagnostic tests
library(knitr)    # For report generation
library(psych)    # For psychological data analysis
options(scipen = 10)  # Avoid scientific notation in output

# Load custom functions from Functions.R
source("Functions.R")
# Set number of permutations for tests
R <- 10000
# Initialize results dataframe
corrsdf <- NULL
```

# Import YouGov result from excel sheet

```{r}
# Import YouGov survey data from Excel
# Note: Previously downloaded from YouGov API
#download.file("https://yougov.co.uk/_pubapis/v5/uk/trackers/britains-mood-measured-weekly/download/", destfile="YouGov/britains-mood-measured-weekly.xlsx")
Yougovdf <- read_excel("yougovoutput.xlsx", sheet="yougovoutput")
# Rename first column to standardize date column name
names(Yougovdf)[1] <- "day"
```

# Import BERT trained models

```{r}
# Set parameters for file generation
epoch <- 2           # Epoch number
query_type <- "Single"  # Query type
similarity <- "Sim"     # Similarity measure

# Get standardized filename
filename <- getfilename(epoch, query_type, similarity)
# Alternative hardcoded filename if needed
#filename <- "Result/baseline_same_model.xlsx"

# Import BERT model outputs
berd <- read_excel(filename, sheet="transpose")
# Rename first column to match YouGov data
names(berd)[1] <- "day"
# Ensure date format consistency
Yougovdf$day <- Yougovdf$day
# Join datasets by date
joind = inner_join(Yougovdf, berd, by="day")
```

##Result for emotion sad

```{r}
Emotion<-"Sad"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (Type: Base Model)")
joind$x <- joind$Sad.x
joind$y <- joind$Sad.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y",  "darkred", "darkblue","Yougov", "Base Model", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Happy

```{r}
Emotion<-"Happy"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (Type: Base Model)")
joind$x <- joind$Happy.x
joind$y <- joind$Happy.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y",  "darkred","darkblue", "Yougov", "Base Model", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Stressed

```{r}
Emotion<-"Stressed"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (Epoch:",epoch,')',sep = "")

joind$x <- joind$Stressed.x
joind$y <- joind$Stressed.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Frustrated

```{r}
Emotion<-"Frustrated"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Frustrated.x
joind$y <- joind$Frustrated.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]FrustratedFrustratedFrustrated
```

##Result for Inspired

```{r}
Emotion<-"Inspired"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Inspired.x
joind$y <- joind$Inspired.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R, label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Apathetic

```{r}
Emotion<-"Apathetic"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Apathetic.x
joind$y <- joind$Apathetic.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label)  

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Lonely

```{r}
Emotion<-"Lonely"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Lonely.x
joind$y <- joind$Lonely.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Optimistic

```{r}
Emotion<-"Optimistic"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Optimistic.x
joind$y <- joind$Optimistic.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Content

```{r}
Emotion<-"Content"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Content.x
joind$y <- joind$Content.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Energetic

```{r}
Emotion<-"Energetic"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Energetic.x
joind$y <- joind$Energetic.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,y_label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Frustrated

```{r}
Emotion<-"Frustrated"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Frustrated.x
joind$y <- joind$Frustrated.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,y_label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

##Result for Bored

```{r}
Emotion<-"Bored"
label <- paste(Emotion," in Yougov and ",Emotion," in Bertweet (",query_type,' Query ',similarity," Epoch:",epoch,')',sep = "")

joind$x <- joind$Bored.x
joind$y <- joind$Bored.y

joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind <- na.omit(joind)
y_label<-paste("Rescaled ",Emotion)
plotTS(joind, joind, "x", "y", "darkblue", "darkred", "Bert", "Yougov", title=label, ylab=y_label, ymin=-2.5, ymax=5,y_label) 

X <- joind$x
Y <- joind$y
ct <- cor.test(X,Y)
corrsdf <- rbind(corrsdf, data.frame(Emotion, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2]))

results <- analyses(joind, joind, R,label)
results$emotion  <- Emotion
results$method <- "Bert"
results$reweight <- "Yes"
results <- results[, c(16,17,18, seq(1,15))]
```

#Compareing results

```{r}
epoch<-2
query_type<-"Multi_mean"
similarity<-"Sim"
filename<-getfilename(epoch, query_type,similarity)
#filename <-"Result/baseline_same_model.xlsx"
berd <- read_excel(filename,sheet="transpose")
names(berd)[1] <- "day"
#Yougovdf$day <- as.Date(Yougovdf$day)
Yougovdf$day <- Yougovdf$day
joind = inner_join(Yougovdf, berd,by="day")

joind$x <- joind$Sad.x

joind$y <- joind$Sad.y
```

```{r}
epoch<-2
query_type<-"Multi_median"
similarity<-"NoSim"
filename<-getfilename(epoch, query_type,similarity)
#filename <-"Result/baseline_same_model.xlsx"
berd2 <- read_excel(filename,sheet="transpose")
names(berd2)[1] <- "day"


joind = inner_join(joind, berd2,by="day")

```

```{r}
joind$z <- joind$Sad
```

```{r}
joind$z <- rollmean(joind$z, k=7, align="right", na.pad = T)
joind$y <- rollmean(joind$y, k=7, align="right", na.pad = T)
joind$x <- rollmean(joind$x, k=7, align="right", na.pad = T)
joind$y <- rollmean(joind$y, k=4, align="right", na.pad = T)
```

```{r}
plotTS2(joind,joind, "x", "y","z", "red", "blue","gray", "yougov", "Similarity","Normal", title="Sad with similarity and without similarity", ylab="Rescaled Sadness", ymin=-2.5, ymax=5) 
```

#Total summery

```{r}
corrsdf <- NULL

inds <- c("happy","sad","energetic","apathetic","inspired","frustrated","optimistic", "stressed","content","bored","lonely","scared")

for (ind in inds)
{
print(ind)
Yougovdf$r <- Yougovdf[[ind]]/100

#Tdf <- read.csv("Data/Volume-total.csv")
#Tdf2 <- read.csv(paste0("Data/Volume-",ind,"YouGov.csv"))

#TwitterUKdf <- inner_join(Tdf, Tdf2, by="day")
#names(TwitterUKdf) <- c("day", "n", "ntweets")
#TwitterUKdf$signal <- TwitterUKdf$ntweets/TwitterUKdf$n
#TwitterUKdf$w <- rollmean(TwitterUKdf$signal, k=7, align="right", na.pad = T)
#TwitterUKdf$ntweetstotal <- rollsum(TwitterUKdf$ntweets, k=7, align="right", na.pad = T)

Twittersel <- left_join(Yougovdf, TwitterUKdf, by="day")
Twittersel$r <- Twittersel$w

X <- Twittersel$r
Y <- Yougovdf$r
ct <- cor.test(X,Y)
print(ct)

print("Corr perm test p-val:")
rndR <- permcor(X,Y,R) # do a permutation test 
print((sum(rndR>=cor(X,Y))+1)/R)

corrsdf <- rbind(corrsdf, data.frame(ind, cor=ct$estimate, corlow = ct$conf.int[1], corhigh = ct$conf.int[2], YGmean=mean(Yougovdf$r), TWmean=mean(Twittersel$ntweetstotal)))

}
```

```{r}
kable(corrsdf)
```

```{r}


corrsdf$emotion <- corrsdf$Emotion

ggplot(corrsdf, aes(x=reorder(emotion, cor), y=cor, fill=as.numeric(reorder(emotion, cor))-6, group=emotion)) + 
  geom_col(stat="identity", color="black", 
           position=position_dodge())  +  scale_fill_gradient2(low='blue', mid="purple", high='red') +
  geom_errorbar(aes(ymin=corlow, ymax=corhigh), width=.2,
                 position=position_dodge(.9))  + coord_flip() + theme_bw()

```
